service: pili

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2
#  stage: dev

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post

resources:
  Resources:
    ShortURLs:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ShortURLs
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: owner
            AttributeType: S
          -
            AttributeName: shortCode
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          -
            IndexName: OwnerShortCode
            KeySchema:
              -
                AttributeName: owner
                KeyType: HASH
              -
                AttributeName: shortCode
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - "url"
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 3


#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
